name: ship_tracker
description: "Dian Mandiri Grup Internal System"

publish_to: "none"

version: 1.6.5+11

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.1.0
  bloc: ^9.0.0
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  file_selector: ^1.0.3
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.2.0
  firebase_core: ^4.2.1
  get_it: ^9.1.0
  go_router: ^17.0.0
  google_sign_in: ^7.2.0
  intl: any
  image_picker: ^1.1.2
  meta: ^1.15.0
  mocktail: ^1.0.4
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  share_plus: ^12.0.1
  simple_barcode_scanner: ^0.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/
    - assets/svgs/

  fonts:
    - family: Inter18pt
      fonts:
        - asset: fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter_18pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter_18pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: fonts/Inter_18pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: fonts/Inter_18pt-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: fonts/Inter_18pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter_18pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Inter_18pt-Thin.ttf
          weight: 100
        - asset: fonts/Inter_18pt-ThinItalic.ttf
          style: italic
    # - family: Inter24pt
    #   fonts:
    #     - asset: fonts/Inter_24pt-ExtraBold.ttf
    #       weight: 800
    #     - asset: fonts/Inter_24pt-ExtraBoldItalic.ttf
    #       weight: 800
    #       style: italic
    #     - asset: fonts/Inter_24pt-Bold.ttf
    #       weight: 700
    #     - asset: fonts/Inter_24pt-BoldItalic.ttf
    #       weight: 700
    #       style: italic
    #     - asset: fonts/Inter_24pt-SemiBold.ttf
    #       weight: 600
    #     - asset: fonts/Inter_24pt-SemiBoldItalic.ttf
    #       weight: 600
    #       style: italic
    #     - asset: fonts/Inter_24pt-Medium.ttf
    #       weight: 500
    #     - asset: fonts/Inter_24pt-MediumItalic.ttf
    #       weight: 500
    #       style: italic
    #     - asset: fonts/Inter_24pt-Light.ttf
    #       weight: 300
    #     - asset: fonts/Inter_24pt-LightItalic.ttf
    #       weight: 300
    #       style: italic
    #     - asset: fonts/Inter_24pt-ExtraLight.ttf
    #       weight: 200
    #     - asset: fonts/Inter_24pt-ExtraLightItalic.ttf
    #       weight: 200
    #       style: italic
    #     - asset: fonts/Inter_24pt-Thin.ttf
    #       weight: 100
    #     - asset: fonts/Inter_24pt-ThinItalic.ttf
    #       weight: 100
    #       style: italic
    #     - asset: fonts/Inter_24pt-Regular.ttf
    #     - asset: fonts/Inter_24pt-Italic.ttf
    #       style: italic
    # - family: Inter28pt
    #   fonts:
    #     - asset: fonts/Inter_28pt-ExtraBold.ttf
    #       weight: 800
    #     - asset: fonts/Inter_28pt-ExtraBoldItalic.ttf
    #       weight: 800
    #       style: italic
    #     - asset: fonts/Inter_28pt-Bold.ttf
    #       weight: 700
    #     - asset: fonts/Inter_28pt-BoldItalic.ttf
    #       weight: 700
    #       style: italic
    #     - asset: fonts/Inter_28pt-SemiBold.ttf
    #       weight: 600
    #     - asset: fonts/Inter_28pt-SemiBoldItalic.ttf
    #       weight: 600
    #       style: italic
    #     - asset: fonts/Inter_28pt-Medium.ttf
    #       weight: 500
    #     - asset: fonts/Inter_28pt-MediumItalic.ttf
    #       weight: 500
    #       style: italic
    #     - asset: fonts/Inter_28pt-Light.ttf
    #       weight: 300
    #     - asset: fonts/Inter_28pt-LightItalic.ttf
    #       weight: 300
    #       style: italic
    #     - asset: fonts/Inter_28pt-ExtraLight.ttf
    #       weight: 200
    #     - asset: fonts/Inter_28pt-ExtraLightItalic.ttf
    #       weight: 200
    #       style: italic
    #     - asset: fonts/Inter_28pt-Thin.ttf
    #       weight: 100
    #     - asset: fonts/Inter_28pt-ThinItalic.ttf
    #       weight: 100
    #       style: italic
    #     - asset: fonts/Inter_28pt-Regular.ttf
    #     - asset: fonts/Inter_28pt-Italic.ttf
    #       style: italic
